### ISSUE TITLE
Add Talk: Mat

### ISSUE THREAD

**Issue by IrinaMonica** [dmahlow/gophercon.es#25]
**Title**
How I Write HTTP Web Services After Eight Years / Mat Ryer 

**Text**
A look at how the speaker builds web services after doing so for the past eight years. Starting with testing, the talk will cover everything a developer needs to deliver working, production ready HTTP web services. Extremely practical, tried and tested patterns that everybody can start using today.

**Bio**
Co-founder of Machine Box, now at Veritone • Computerperson, gopher, speaker, author • him/his/tabs

[Website](http://matryer.com/)
[Twitter](https://twitter.com/matryer)

![mat](https://user-images.githubusercontent.com/47850422/54996767-78315d80-4fca-11e9-9f74-e5c20aede142.png)

**Comment by matryer** [comment]
New bio:

```
Co-founder of Machine Box, now at Veritone • Computerperson, gopher, speaker, author • him/his/tabs
```
